In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
dataset_1 = pd.read_csv('hackathon_data/stock_1_train.csv')

In [3]:
dataset_1

          col_0     col_1     col_2     col_3     col_4      target
0      1.574674  0.170111 -0.045997  0.758763  0.185289  223.453581
1     -0.802095 -0.246373  1.640907 -0.141742 -0.163337  211.253687
2      0.216712  0.468679 -0.786830 -0.152416  0.293351  280.980886
3      0.864578 -0.343601 -1.563815  0.621198  1.124796  266.650511
4      1.465125 -0.861386 -0.950072 -0.218991 -0.597203  216.206945
...         ...       ...       ...       ...       ...         ...
19994  1.303237  0.474954  0.263489 -0.700718 -0.341041  221.232684
19995 -0.187980 -0.328975 -0.016282  0.577255 -0.647026  248.174244
19996 -0.349532  1.305488  0.273586  0.797979  0.720430  278.366141
19997 -0.443370  1.096142 -0.722360 -0.594727  0.010247  297.370878
19998  2.526569  0.297506 -1.783894 -0.360988 -1.255813  250.789915

[19999 rows x 6 columns]

In [4]:
dataset_2 = pd.read_csv('hackathon_data/stock_2_train.csv')

In [5]:
dataset_2

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,target
0,1.749549,1.379060,1.466218,-0.040868,-1.289326,2.482270,0.062953,1.228708,-0.550275,-2.562374,1.470103,0.449527,0.329788,0.182796,-1.637142,124.306905
1,-2.183235,1.022913,0.350338,0.310195,0.303455,-2.060162,-0.985166,-0.451727,-0.748743,0.982296,1.143162,1.303832,-1.210172,-0.968907,0.049078,299.009603
2,1.439336,0.164688,-0.248423,-1.783725,-1.619735,-1.835699,0.379339,-1.362249,1.255577,-1.683831,-0.597999,-0.035882,0.335943,0.075771,-0.517127,244.389408
3,-0.138912,0.848406,0.554161,-0.748682,0.136699,1.490442,-0.831366,0.145167,-0.193161,-0.732599,0.864937,0.693117,-1.050654,0.071236,0.031818,195.727263
4,-0.632556,1.872235,-0.047678,1.768425,-1.398392,0.518185,2.071083,0.029751,-0.264004,-1.450831,2.048307,1.893192,2.120943,1.697403,-1.377064,264.674971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,-0.271592,1.541580,0.467276,-1.288850,1.095383,-0.891514,0.743359,0.553165,0.616310,0.440584,1.043551,1.391736,-0.247780,0.896610,1.181075,293.261550
1495,0.988532,0.475438,-0.624721,0.182097,0.572287,0.047053,0.480243,-0.862951,1.992832,-1.025807,1.549324,1.093389,0.639595,-0.385795,1.167205,277.517177
1496,-0.317563,-0.441448,0.762197,-1.770736,1.574280,0.135529,0.610018,0.725078,-0.708059,2.291798,-1.913030,-1.458059,1.316276,1.553349,0.811855,188.538130
1497,-1.639221,-1.199935,0.299057,0.618715,-0.283385,0.892606,-0.796554,-0.399692,-0.302078,0.992037,-0.913405,-1.080435,-0.423477,-1.431358,-0.052105,192.548273
1498,0.943230,-0.581174,-1.042654,1.646186,0.697622,0.977096,0.454496,-0.093151,-0.279604,0.215326,-0.029348,-0.500978,-0.447780,-0.096861,2.020873,189.833101